myproject/myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views 


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login_view'),
    path('profile/', views.profile_view, name='profile_view'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    #reset password
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    #settings
    path('settings/', views.settings_view, name='settings'),
    path('change-password/', views.change_password, name='change_password'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('', include('enrollment.urls')),
    path('', include('benefits.urls')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/benefits/models.py
from django.db import models
from enrollment.models import Employee
# Create your models here.
class Benefits(models.Model):
    name = models.CharField(max_length=255)
    duration = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name
    
# application model
class Application(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    #employee_id = models.CharField(max_length=255)
    #last_name = models.CharField(max_length=255)
    #first_name = models.CharField(max_length=255)
    
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Denied', 'Denied')
    ]
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    date_applied = models.DateField(auto_now_add=True)
    benefits = models.ManyToManyField(Benefits)

    def __str__(self):
        return f"{self.employee.first_name} {self.employee.last_name} - {self.date_applied}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.status = 'Pending'
        super().save(*args, **kwargs)

myproject/enrollment/models.py
from django.db import models
#from benefits.models import Benefits

# Create your models here.
class Employee(models.Model):
    EMPLOYEE_STATUS_CHOICES = [
        ('active', 'Active'),
        ('on leave', 'On Leave'),
        ('terminated', 'Terminated')
    ]
    
    EMPLOYEE_TYPE_CHOICES = [
        ('full-time', 'Full-Time'),
        ('part-time', 'Part-Time'),
        ('temporary', 'Temporary')
    ]
    password = models.CharField(max_length=255, default='1234', null=True)
    employee_id = models.AutoField(primary_key=True, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    email_address = models.EmailField(max_length=100, unique=True)
    department = models.CharField(max_length=50, blank=True, null=True)
    position = models.CharField(max_length=50, blank=True, null=True)
    hire_date = models.DateField()
    salary = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    employee_status = models.CharField(
        max_length=10,
        choices=EMPLOYEE_STATUS_CHOICES,
        default='active'
    )
    employee_type = models.CharField(
        max_length=10,
        choices=EMPLOYEE_TYPE_CHOICES,
        default='full-time'
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.employee_id}"
    class Meta:
        db_table = 'employee'
        
class EmployeeBenefits(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    #benefit = models.ForeignKey(Benefits, on_delete=models.CASCADE)
    health_insurance = models.BooleanField(default=False)
    dental_insurance = models.BooleanField(default=False)
    vision_insurance = models.BooleanField(default=False)
    life_insurance = models.BooleanField(default=False)
    retirement_savings = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.employee.first_name} {self.employee.last_name} - Benefits"
    class Meta:
        app_label = 'enrollment'
        #db_table = 'employee_benefits'

myproject/myapp/models.py
from django.db import models
from enrollment.models import Employee

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    #class Meta:
        #db_table = 'users'

class Dependent(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    relationship = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name} - Dependent of {self.employee.first_name} {self.employee.last_name}"
    class Meta:
        db_table = 'dependent'

class Beneficiary(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    relationship = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name} - Beneficiary of {self.employee.first_name} {self.employee.last_name}"
    class Meta:
        db_table = 'beneficiary'

myproject/myapp/forms.py
from django import forms
from enrollment.models import Employee

class EmployeeUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = [
            'date_of_birth', 'email_address', 'department', 'position', 
            'hire_date', 'salary', 'employee_status', 'employee_type'
        ]

#form stuff: still tryna figure things out
class RegisterForm(forms.ModelForm):
    employee_id = forms.IntegerField(label='Employee ID')
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = Employee
        fields = ['employee_id', 'email']  # Include email and employee_id fields

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords don\'t match.')
        return password2

    def save(self, commit=True):
        instance = super(RegisterForm, self).save(commit=False)
        instance.set_password(self.cleaned_data['password1'])
        if commit:
            instance.save()
        return instance
#for the dependents and beneficiary
from .models import Dependent, Beneficiary

class DependentForm(forms.ModelForm):
    class Meta:
        model = Dependent
        fields = ['name', 'date_of_birth', 'relationship']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'})
        }

class BeneficiaryForm(forms.ModelForm):
    class Meta:
        model = Beneficiary
        fields = ['name', 'date_of_birth', 'relationship']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'})
        }

myproject/myapp/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import loader
from django.shortcuts import render, redirect
from enrollment.models import Employee
from .models import User
from django.contrib.auth.decorators import login_required
from .forms import EmployeeUpdateForm
#from django.contrib.auth import authenticate, login
from .models import Beneficiary,Dependent
from django.shortcuts import render, redirect
from benefits.models import Application

def login_view(request):
    if request.method == 'POST':
        employee_id = request.POST.get('employee_id')
        password = request.POST.get('password')
        try:
            employee = Employee.objects.get(employee_id=employee_id, password=password)
            # If user exists, set session variable and redirect to profile
            request.session['employee_id'] = employee.employee_id
            return redirect('profile')
        except Employee.DoesNotExist:
            # Return an 'invalid login' error message.
            return render(request, 'login.html', {'error_message': 'Invalid Employee ID or password'})
    elif request.method == 'GET':
        # This block will be executed when the form is loaded
        # and a GET request is made to the login page
        print('smths not right')
        return render(request, 'login.html')
    else:
        # This block will be executed for any other request method
        # It's a good idea to log these cases for debugging purposes
        print(f'Unexpected request method: {request.method}')
        return HttpResponseBadRequest('Bad request method')
    
#@login_required
def profile_view(request):
    # Assuming employee_id is stored in session
    employee_id = request.session.get('employee_id')
    print(f"Employee ID from session: {employee_id}")

    if employee_id:
        try:
            employee = Employee.objects.get(employee_id=employee_id)
            applications = Application.objects.filter(employee=employee)
            beneficiaries = Beneficiary.objects.filter(employee=employee)
            dependents = Dependent.objects.filter(employee=employee)

            if request.method == 'POST':
                form = EmployeeUpdateForm(request.POST, instance=employee)
                if form.is_valid():
                    form.save()
                    return redirect('profile')  # Redirect to the profile page after saving
            else:
                form = EmployeeUpdateForm(instance=employee)

            context = {
                'form': form,
                'employee': employee,
                'applications': applications,
                'dependents': dependents,
                'beneficiaries': beneficiaries,

            }
            print(f"Employee found: {employee.first_name} {employee.last_name}")
            return render(request, 'profile.html', context)
        except Employee.DoesNotExist:
            print("Employee not found in database")
            # Handle the case where the employee does not exist
            return redirect('register')  # Redirect to the enrollment page or login page
    else:
        # Handle the case where employee_id is not in the session
        return redirect('login')   # Redirect to the enrollment page or login page

#to handle form submission
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            employee = form.save()  # Save the employee and get the instance
            request.session['employee_id'] = employee.employee_id            
            return redirect('profile')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})

from django.contrib.auth import logout as auth_logout
#from django.urls import reverse


def logout_view(request):
    print("Logging out...")
    auth_logout(request)
    print("Redirecting to login...")
    return redirect('login_view')

def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render())
def settings_view(request):
    employee_id = request.session.get('employee_id')

    employee = Employee.objects.get(employee_id=employee_id)
    context = {
                'employee': employee,
            }
    return render(request, 'user_settings.html', context)
## for benefitiarty and dependents meow
from .forms import DependentForm, BeneficiaryForm

def add_dependent(request):
    if request.method == 'POST':
        form = DependentForm(request.POST)
        if form.is_valid():
            dependent = form.save(commit=False)
            dependent.employee = request.user.employee  # Assuming employee is logged in
            dependent.save()
            return redirect('some-redirect-url')
    else:
        form = DependentForm()
    return render(request, 'add_dependent.html', {'form': form})

def add_beneficiary(request):
    if request.method == 'POST':
        form = BeneficiaryForm(request.POST)
        if form.is_valid():
            beneficiary = form.save(commit=False)
            beneficiary.employee = request.user.employee  # Assuming employee is logged in
            beneficiary.save()
            return redirect('some-redirect-url')
    else:
        form = BeneficiaryForm()
    return render(request, 'add_beneficiary.html', {'form': form})
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {'form': form})

myproject/myapp/templates/favicon.html
{% load static %}
<link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

myproject/myapp/templates/footer.html
<footer>
    {% load static %}  <link rel="stylesheet" href="{% static 'footer.css' %}"> 
    <p>&copy; 2024 All Rights Reserved. Built with <span style="color: red;">&#x2764;</span> by <a href="https://github.com/veranyagaka">Vera Nyagaka</a>.</p>
  </footer>
  

myproject/myapp/templates/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Benefits Pro - Your Employee Benefits Hub</title>
    <link rel ="stylesheet" href="{% static 'index.css' %}">
    {% include 'favicon.html' %}
</head>

<body>
    <header>
        <h1>Benefits Pro</h1>
        <p>Your one-stop shop for managing employee benefits.</p>
    </header>
    <main>
        <div class="welcome-message">
            <h2>Welcome to a Brighter Benefits Future</h2>
            <p>Benefits Pro empowers HR professionals to streamline employee benefit administration, simplify enrollment, and ensure a positive experience for your workforce.</p>
            <button onclick="window.location.href='/login'">Login Here!</button>
        </div>
        <div class="benefits-highlight">
            <h3>Benefits Made Easy</h3>
            <ul>
                <li>Effortless Management: Manage health insurance, retirement plans, and more in one central location.</li>
                <li>Simplified Enrollment: Streamline enrollment processes for employees.</li>
                <li>Enhanced Communication: Keep employees informed and engaged with clear benefit information.</li>
                <li>Data-Driven Insights: Gain valuable insights to improve your benefits program.</li>
            </ul>
        </div>
    </main>
    {% include 'footer.html' %} 

</body>
</html>

myproject/myapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Benefits Pro - Login</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" rel="stylesheet">
  {% load static %}  <link rel="stylesheet" href="{% static 'login.css' %}">  
  {% include 'favicon.html' %}

  </head>
<body>
  <header>
    <h1>Benefits Pro</h1>
  </header>
  <main>
    <div class="container d-flex flex-wrap">  <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h2>Login</h2>
          </div>
          <div class="card-body">
            <form action="{% url 'login_view' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="employee_id">Employee ID</label>
                <div class="input-group">
                  <span class="input-group-text"><i class="fa fa-user"></i></span>
                  <input type="text" class="form-control" id="employee_id" name="employee_id" required>
                </div>
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <div class="input-group">
                  <span class="input-group-text"><i class="fa fa-lock"></i></span>
                  <input type="password" class="form-control" id="password" name="password" required>
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Login</button>
            </form>
            {% if request.method == 'POST' and error_message %}
            <div class="error">{{ error_message }}</div>
          {% endif %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class = "vera">

        <p class="lead">Benefits Pro Login Requirements</p>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><span class="fa fa-check text-success"></span> Be a registered employee of the company</li>
          <li class="list-group-item"><span class="fa fa-check text-success"></span> Possess a valid employee ID and password</li>
          <li class="list-group-item">
            <span class="fa fa-info-circle text-info"></span> For first-time users, please <a href="{% url 'register' %}">register here</a>
          </li>
          <li class="list-group-item">
            <span class="fa fa-info-circle text-info"></span> If you forgot your password, <a href=" {% url 'password_reset' %}">click here</a> to reset it
          </li>
        </ul>
      </div>
    </div>
  </main>
  {% include 'footer.html' %} 

</body>
</html>

myproject/myapp/templates/logout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Benefits Pro - Logout</title>
  <link rel="stylesheet" href="{% static 'logout.css' %}">
  {% include 'favicon.html' %}

</head>
<body>
  <header>
    <h1>Benefits Pro</h1>
  </header>
  <main class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card text-center">
      <div class="card-body">
        <h2 class="mb-4">Logout Successful!</h2>
        <p>You have been successfully logged out of the Benefits Pro application.</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Login Again</a>
        <br>
        <a href="{% url 'index' %}" class="btn btn-secondary mt-2">Return to Home Page</a>
      </div>
    </div>
  </main>
  {% include 'footer.html' %} 

</body>
</html>

myproject/myapp/templates/navigation.html
<!DOCTYPE html>
<html>
<head>
  <title>Navigation Bar</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
 body {
  background-color: #181818;
  color: #fff;
  font-family: Arial, sans-serif;
}

.nav-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 20px;
  background-color: #242424;
  border-bottom: 1px solid #333;
}

.logo {
  display: flex;
  align-items: center;
}

.logo img {
  width: 30px;
  height: 30px;
  margin-right: 10px;
}

.search-bar {
  background-color: #303030;
  border: 1px solid #444;
  border-radius: 25px;
  padding: 5px 15px;
  width: 300px;
  margin-right: 20px;
  display: flex;
}

.search-bar input {
  background-color: #303030;
  border: none;
  color: #fff;
  font-size: 16px;
  padding: 5px 10px;
  width: 100%;
  border-radius: 25px;
}

.search-bar input:focus {
  outline: none;
}

.icons {
  display: flex;
  align-items: center;
}

.icon {
  width: 35px;
  height: 35px;
  margin-right: 15px;
  border-radius: 50%;
  background-color: #242424;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: background-color 0.2s ease;
}

.icon:hover {
  background-color: #303030;
}

.icon-img {
  width: 20px;
  height: 20px;
}

.tooltip {
  position: absolute;
  background-color: #303030;
  color: #fff;
  padding: 5px 10px;
  border-radius: 5px;
  visibility: hidden;
  opacity: 0;
  transition: opacity 0.2s ease;
}

.tooltip:after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: transparent transparent #303030 transparent;
}

.icon:hover .tooltip {
  visibility: visible;
  opacity: 1;
}

.icon:hover .tooltip {
  visibility: visible;
  opacity: 1;
}

.icon:hover .tooltip {
  visibility: visible;
  opacity: 1;
}

.icon:hover .tooltip {
  visibility: visible;
  opacity: 1;
}
.menu-icon {
    margin-right: auto; 
}

.menu-icon i {
    color: #fff; 
}
.settings-icon {
    margin-left: auto; 
}

.settings-icon i {
    color: #fff; 
}
  </style>
</head>
<body>
  <div class="nav-bar">
    <div class="logo">
      <img src="#" alt="BenefitsPro Logo">
      <span>BenefitsPro</span>
    </div>
    <div class="menu-icon icon" data-tooltip="Menu">
        <i class="fas fa-bars"></i>
        <span class="tooltip">Menu</span>
    </div>
    <div class="search-bar">
      <input type="text" placeholder="Search">
      <span class="tooltip">Search</span>
      <div class="icon" data-tooltip="Search">
        <i class="fas fa-search"></i>
      </div>
    </div>
    <div class="icons">
      <div class="icon" data-tooltip="Notification">
        <i class="fas fa-bell"></i>
        <span class="tooltip">Notification</span>
      </div>

      <div class="settings-icon icon" data-tooltip="Settings">
        <i class="fas fa-cog"></i>
        <span class="tooltip">Settings</span>
    </div>
      <div class="icon" data-tooltip="Account">
        <i class="fas fa-user"></i>
        <span class="tooltip">Account</span>
      </div>
    </div>
  </div>

  <script>
    const icons = document.querySelectorAll('.icon');
    icons.forEach(icon => {
      icon.addEventListener('mouseover', () => {
        icon.querySelector('.tooltip').style.visibility = 'visible';
        icon.querySelector('.tooltip').style.opacity = 1;
      });
      icon.addEventListener('mouseout', () => {
        icon.querySelector('.tooltip').style.visibility = 'hidden';
        icon.querySelector('.tooltip').style.opacity = 0;
      });
    });
  </script>
</body>
</html>

myproject/myapp/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'profile.css' %}">
  <title>Profile</title>
  {% include 'favicon.html' %}

</head>
<body>
  {% include 'sidebar.html' %} 

    <div class="main-content">
      <!-- Instructions part -->
      <section class="profile-instructions">
        <h2>Profile Instructions</h2>
        <p>Follow these steps to ensure a smooth and successful application process:</p>
        <ol>
          <li>
            <b>Profile Completion:</b> Navigate through profile tabs, starting with "Personal Details," filling out all required information and leaving optional fields blank if they don't apply.
          </li>
          <li>
            <p>Dependent Information (Optional): If you have dependents and want to designate a beneficiary, please provide their information and details.</p>
          </li>
          <li>
            <p>Go to the "Documents" tab and upload all necessary supporting documents for your applications.</p>
          </li>
          <li>
            <p><b>Benefits:</b> Once your profile is complete, navigate to the "Benefits" menu and select "New Application" to apply for benefits.</p>
          </li>
          <li>
            <b>Important Note:</b> Applications missing required information (marked with a red asterisk: *) will NOT be considered. Ensure all necessary details are filled out before submitting your application.
          </li>
        </ol>
        <p>By following these instructions, you can complete your profile and submit applications for benefits efficiently.</p>
      </section>
      <!-- Ends here -->
      <div class="employee-details">
        <h2>Employee Details</h2>
        <ul class="tabs">
          <li class="tab active" data-target="personal-details">Personal Details</li>
          <li class="tab" data-target="beneficiary-details">Beneficiary</li>
          <li class="tab" data-target="dependents">Dependents</li>
        </ul>
        <ul id="personal-details" class="details-list active">
          <li>Date of Birth: {{ employee.date_of_birth }}</li>
          <li>Email Address: {{ employee.email_address }}</li>
          <li>Department: {{ employee.department }}</li>
          <li>Position: {{ employee.position }}</li>
          <li>Hire Date: {{ employee.hire_date }}</li>
          <li>Salary: {{ employee.salary }}</li>
          <li>Employee Status: {{ employee.get_employee_status_display }}</li>
          <li>Employee Type: {{ employee.get_employee_type_display }}</li>
        </ul>
        <button id="edit-info-btn">Edit Information</button>
        <div id="edit-info-form" style="display: none;">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update Information</button>
          </form>
        </div>
        <ul id="beneficiary-details" class="details-list" >
          <!-- Add your beneficiary details here -->
          <h2>Beneficiary Information (Optional)</h2>

          {% if beneficiaries %}
            {% for beneficiary in beneficiaries %}
              <li>Name: {{ beneficiary.name }}</li>
              <li>Date of Birth: {{ beneficiary.date_of_birth }}</li>
              <li>Relationship: {{ beneficiary.relationship }}</li>
            {% endfor %}
          {% else %}
            <p>You haven't added any beneficiary information yet.</p>
          {% endif %}
          <div>
            <div id="add-dependent-form" style="display: none;">
              <form method="post" action="#">
                  {% csrf_token %}
                  {{ dependent_form.as_p }}
                  <button type="submit">Add Dependent</button>
              </form>
          </div>
        </div>
        
        </ul>
        <ul id="dependents" class="details-list">
          <!-- Dependents Details -->
          <h2>Dependent Information (Optional)</h2>

        {% if dependents %}
        {% for dependent in dependents %}
            <li>Name: {{ dependent.name }}</li>
            <li>Date of Birth: {{ dependent.date_of_birth }}</li>
            <li>Relationship: {{ dependent.relationship }}</li>
        {% endfor %}
    {% else %}
        <p>You haven't added any dependent information yet.</p>
    {% endif %}   
              <a href="#" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this dependent?');">Delete</a>
              <div id="edit-info-form" style="display: none;">
                <form method="post">
                  {% csrf_token %}
                  {{ dependent_form.as_p }}
                  <button type="submit">Update Dependent</button>
                </form>
              </div>
              <button id="add-dependent-btn">Add Dependent</button>
        </ul>
       </div>

      <h2>Applications</h2>
      <table>
        <thead>
          <tr>
            <th>Benefit Program</th>
            <th>Date Applied</th>
            <th>Status</th>
            <th>Documents</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <!--Working on the applications part rn -->
          {% for application in applications %}
          <tr>
            <td> {% for benefit in application.benefits.all %}
              {{ benefit.name }}{% if not forloop.last %}, {% endif %}
          {% endfor %}</td>
            <td>{{ application.date_applied }}</td>
            <td class="
            {% if application.status == 'Pending' %}
                status-pending
            {% elif application.status == 'Approved' %}
                status-approved
            {% elif application.status == 'Denied' %}
                status-denied
            {% endif %}
        ">{{ application.get_status_display }}</td>
            <td>{{ application.documents }}</td>
            <td><a href="#" class="btn">View Application</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
  <script>
    const editInfoBtn = document.getElementById('edit-info-btn');
    const editInfoForm = document.getElementById('edit-info-form');

    editInfoBtn.addEventListener('click', () => {
      editInfoForm.style.display = editInfoForm.style.display === 'none' ? 'block' : 'none';
    });
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', () => {

    const tabs = document.querySelectorAll('.tab');
    const detailsLists = document.querySelectorAll('.details-list');

    tabs.forEach(tab => {
        tab.addEventListener('click', function() {
            // Remove 'active' class from all tabs and details lists
            tabs.forEach(t => t.classList.remove('active'));
            detailsLists.forEach(list => list.classList.remove('active'));

            // Add 'active' class to the clicked tab
            this.classList.add('active');

            // Show the corresponding details list
            const selectedTab = this.getAttribute('data-tab');
            document.getElementById(selectedTab).classList.add('active');
        });
    });
    });
  </script>
  <script>
    function toggleEditForm(formId) {
        const form = document.getElementById(formId);
        form.style.display = form.style.display === 'none' ? 'block' : 'none';
    }
</script>
  {% include 'footer.html' %}
</body>
</html>

myproject/myapp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Benefits Pro - Register</title>
  {% load static %}  <link rel="stylesheet" href="{% static 'register.css' %}">  
  {% include 'favicon.html' %}

  </head>
<body>
  <header>
    <h1>Benefits Pro - Register</h1>
  </header>
  <main>
    <div class="container">
        <h2>Unlock Your Benefits</h2>
        <h4>Get the most out of your employment with our comprehensive benefits program. </h4>
            <h4>Register now!</h4>
              <form method="post">
        {% csrf_token %}  {{ form.as_p }}  <button type="submit" class="btn btn-primary">Register</button>
      </form>
    </div>
  </main>
  {% include 'footer.html' %} 

</body>
</html>